"""
Suggestions Router

Returns daily suggestions generated by LLM for the user.
"""

from datetime import datetime, timezone
from uuid import UUID
from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select

from ....infrastructure.container import ApplicationContainer
from ...dependencies import get_current_user_id
from .deps import get_container
from ....infrastructure.database.models import DailySuggestionModel


router = APIRouter(redirect_slashes=False)


@router.get("/suggestions", summary="Get suggestions for a given day", response_model=List[str])
async def get_daily_suggestions(
    date: str = Query(None, description="YYYY-MM-DD in UTC"),
    user_id: UUID = Depends(get_current_user_id),
    container: ApplicationContainer = Depends(get_container),
):
    try:
        # Parse date; default to today UTC at midnight
        if date:
            try:
                dt = datetime.strptime(date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
            except ValueError:
                raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid date format. Use YYYY-MM-DD.")
        else:
            now = datetime.now(timezone.utc)
            dt = now.replace(hour=0, minute=0, second=0, microsecond=0)

        async with container.database.get_session() as session:
            stmt = select(DailySuggestionModel).where(
                DailySuggestionModel.user_id == user_id,
                DailySuggestionModel.date == dt,
            )
            res = await session.execute(stmt)
            row = res.scalar_one_or_none()
            if not row:
                return []
            return list(row.suggestions or [])
    except HTTPException:
        raise
    except Exception:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Failed to retrieve suggestions")


