from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime

class ChatMessage(BaseModel):
    """Represents a single chat message"""
    content: str
    timestamp: datetime
    role: str = Field(..., pattern="^(user|assistant|system)$")
    metadata: Optional[Dict[str, Any]] = None

class ChatResponse(BaseModel):
    """Response from agent chat endpoint"""
    message: str
    agent_type: str
    user_message: str
    timestamp: Optional[datetime] = None
    session_id: Optional[str] = None
    
    class Config:
        schema_extra = {
            "example": {
                "message": "I understand you're feeling stressed. Let's work through this together.",
                "agent_type": "therapy",
                "user_message": "I'm having a difficult day",
                "timestamp": "2024-01-15T10:30:00Z"
            }
        }

class AgentResponse(BaseModel):
    """Generic agent response model"""
    success: bool
    message: str
    data: Optional[Dict[str, Any]] = None
    agent_type: Optional[str] = None
    error: Optional[str] = None
    
    class Config:
        schema_extra = {
            "example": {
                "success": True,
                "message": "Agent operation completed successfully",
                "data": {"agent_status": "active"},
                "agent_type": "therapy"
            }
        }

class AgentStatus(BaseModel):
    """Agent status information"""
    active: bool
    agent_type: str
    last_interaction: Optional[datetime] = None
    memory_summary: Optional[str] = None
    personality: str
    conversation_length: int = 0
    
class ConversationSummary(BaseModel):
    """Summary of a conversation session"""
    session_id: str
    start_time: datetime
    end_time: Optional[datetime] = None
    message_count: int
    topics_discussed: List[str] = []
    mood_progression: Optional[Dict[str, Any]] = None
    insights: List[str] = []

class AgentMetrics(BaseModel):
    """Agent performance and usage metrics"""
    total_conversations: int
    total_messages: int
    average_session_length: float
    most_common_topics: List[str] = []
    user_satisfaction: Optional[float] = None
    last_active: Optional[datetime] = None

class EmotionalInsight(BaseModel):
    """Emotional insight generated by agent"""
    insight_type: str
    description: str
    confidence_score: float = Field(ge=0.0, le=1.0)
    suggested_actions: List[str] = []
    generated_at: datetime

class WellnessRecommendation(BaseModel):
    """Wellness recommendation from agent"""
    category: str  # e.g., "mindfulness", "physical", "social"
    title: str
    description: str
    difficulty_level: str = Field(..., pattern="^(beginner|intermediate|advanced)$")
    estimated_duration: str  # e.g., "5 minutes", "30 minutes"
    benefits: List[str] = []

class TherapyGoal(BaseModel):
    """Therapy goal tracking"""
    goal_id: str
    title: str
    description: str
    target_date: Optional[datetime] = None
    progress_percentage: float = Field(ge=0.0, le=100.0)
    milestones: List[str] = []
    current_status: str = Field(..., pattern="^(not_started|in_progress|completed|paused)$")

class CopingStrategy(BaseModel):
    """Coping strategy information"""
    strategy_id: str
    name: str
    description: str
    category: str  # e.g., "breathing", "cognitive", "behavioral"
    effectiveness_rating: Optional[float] = Field(None, ge=1.0, le=10.0)
    last_used: Optional[datetime] = None
    usage_count: int = 0

class SessionNote(BaseModel):
    """Note from a therapy or wellness session"""
    note_id: str
    session_id: str
    content: str
    note_type: str = Field(..., pattern="^(insight|goal|homework|observation)$")
    created_at: datetime
    created_by: str = "agent"  # or "user" 