"""fix_custom_emotion_color_range

Revision ID: da94b43245f1
Revises: add_breathing_patterns
Create Date: 2025-08-07 20:38:55.863755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'da94b43245f1'
down_revision = 'add_breathing_patterns'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###